[project]
name = "cf-wv2s-ip-rule"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "requests>=2.32.3",
]
