name: Update Addressesapi

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run main.py
        run: python main.py

      - name: Check for changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Automated update from GitHub Actions"
          else
            echo "No changes to commit."
          fi

      - name: Push changes
        if: success() && steps.check-for-changes.outputs.changes_detected == 'true'
        run: git push